name: Docker CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  DOCKER_IMAGE_NAME: grosent/elsight_devops_flask_api # Replace with your Docker Hub username and image name
  DOCKER_FILE_PATH: ./app/Dockerfile # Path to your Dockerfile, typically in the root of the repo

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx for multi-platform builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # GitHub Secret for Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # GitHub Secret for Docker Hub password

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (current directory)
          file: ${{ env.DOCKER_FILE_PATH }} # Path to the Dockerfile
          push: true # Push the image to the registry
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest # Tag the image as 'latest'
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} # Tag with the Git SHA for specific versioning
          cache-from: type=gha # Cache layers to speed up builds
          cache-to: type=gha,mode=max # Store cache for future builds
